name: The Attic
url: https://indigo.re

markdown: kramdown
redcarpet:
  extensions: ["tables"]
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
permalink: /posts/:categories/:year-:month-:day-:title.html
collections:
  posts_data:
    output: true
    permalink: /posts/:path
defaults:
  -
    scope:
      # "" is for every file
      path: ""
    values:
      layout: mine
      lang: en
